testing

diff --git a/source/test/max-stack-height/test_3/Makefile b/source/test/max-stack-height/test_3/Makefile
--- a/source/test/max-stack-height/test_3/Makefile
+++ b/source/test/max-stack-height/test_3/Makefile
@@ -7,21 +7,25 @@ loadso=${HOME}/Github/binary-decompilation/source/Release+Asserts/lib/LLVMmax_st
 
 all:	test
 
-
-
 test: 
-	${RUN_SH} ${PROG_PREFIX} 64 	${ENTRY_POINT} 
-	${OPT} -load=${loadso} -ssh  -debug ${PROG_PREFIX}.ll  -o /dev/null &>  log
-	sed -e '/Args:/,/Subtarget features:/d' log > log.mod	
-	sed -e '/Args:/,/Subtarget features:/d'  ${PROG_PREFIX}.gold >  ${PROG_PREFIX}.mod
-	diff -q log.mod  ${PROG_PREFIX}.mod
+	@${RUN_SH} ${PROG_PREFIX} 64 	${ENTRY_POINT} 
+	@${OPT} -load=${loadso} -ssh  -debug ${PROG_PREFIX}.ll  -o /dev/null &>  log
+	@sed -e '/Args:/,/Subtarget features:/d' log > log.mod	
+	@sed -e '/Args:/,/Subtarget features:/d'  ${PROG_PREFIX}.gold >  ${PROG_PREFIX}.mod
+	@diff -w -q log.mod  ${PROG_PREFIX}.mod
+	@if [ $$? != 0  ]; then \
+		echo 	"${PROG_PREFIX} FAILED" ;\
+	fi
 
-	for file in `ls *.dot` ; do \
+	@for file in `ls *.dot` ; do \
 	  gold=$$(echo $$file | sed 's/dot/gold/g') ; \
-	  echo Diff $$gold  $$file  ; \
-	  diff -q  $$gold $$file; \
-	  echo;\
+	  diff -w -q  $$gold $$file; \
+		if [ $$? != 0  ]; then \
+			echo 	"${PROG_PREFIX} FAILED" ;\
+		fi \
 	done  
+
+	@echo "${PROG_PREFIX} Pass"
 
 clean:
 	../utils/clearall.sh
